---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart NetBox services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
  loop:
    - netbox.service
    - netbox-rq.service

